name: Deploy documentation to the ss3 website

on:
  workflow_call:

jobs:
  update-ss3-version:
    runs-on: ubuntu-20.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Get the latest stock synthesis binaries
        run: |
         curl https://api.github.com/repos/nmfs-stock-synthesis/stock-synthesis/releases/latest | grep "browser_download_url" | grep -Eo 'https://[^\"]*' | xargs wget

      - name: Move exes to the right location
        run: |
          mv ss_linux inst/bin/Linux64/ss
          mv ss_win.exe inst/bin/Windows64/ss.exe
          mv ss_osx inst/bin/MacOS/ss
          rm ss_opt_osx
          rm ss_opt_linux
          rm ss_opt_win.exe

      - name: Change permissions for mac and linux exes
        run: |
          chmod a+x inst/bin/Linux64/ss
          chmod a+x inst/bin/MacOS/ss

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Update ss3 binaries'
          branch: update-ss3
          title: 'Update ss3 binaries'
          body: |
           Auto-generated by [update-ss3-version.yml][1]

            [1]: https://github.com/nmfs-stock-synthesis/workflows/tree/main/.github/workflows/update-ss3-version.yml
